# velodyne:
velodyne_driver_node:
    ros__parameters:
        device_ip: 192.168.131.20
        gps_time: false
        time_offset: 0.0
        enabled: true
        read_once: false
        read_fast: false
        repeat_delay: 0.0
        frame_id: velodyne_frame
        model: VLP16
        rpm: 600.0
        port: 2368
        timestamp_first_packet: false
velodyne_laserscan_node:
    ros__parameters:
        ring: -1
        resolution: 0.007
velodyne_transform_node:
    ros__parameters:
        calibration: /root/ros2_ws/src/HuskyUGV/husky_base/config/VLP16db.yaml
        model: VLP16
        min_range: 0.9
        max_range: 130.0
        view_direction: 0.0
        fixed_frame: velodyne_frame
        target_frame: velodyne_frame
        organize_cloud: true