diagnostic_aggregator:
  ros__parameters:
    path: /Husky A-200
    husky:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Husky
      find_and_remove_prefix: ['husky_hardware: ']
      expected: [
        'husky_hardware: power_status',
        'husky_hardware: system_status',
        'husky_hardware: safety_status',
        'husky_hardware: software_status']
      timeout: 5.0
    twist_mux:
      type: diagnostic_aggregator/GenericAnalyzer
      path: TwistMux
      find_and_remove_prefix: ['twist_mux:']
