name: husky_ci

on:
  push:
    branches: [humble-devel]
  pull_request:
    branches: [humble-devel]
  schedule:
    - cron: '0 4 * * *' # every day at 4 AM (UTC)

jobs:
  husky_humble_testing_ci:
    name: Humble Testing
    strategy:
      matrix:
        distro: [humble]
        repo: [testing]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{matrix.distro}}
          ROS_REPO: ${{matrix.repo}}
  husky_humble_main_ci:
    name: Humble Main
    strategy:
      matrix:
        distro: [humble]
        repo: [main]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{matrix.distro}}
          ROS_REPO: ${{matrix.repo}}
