# This is a format job. Pre-commit has a first-party GitHub action, so we use
# that: https://github.com/pre-commit/action

name: Format

on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble-devel
  push:
    branches:
      - humble-devel

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install clang-format
      run: sudo apt-get install clang-format
    - uses: pre-commit/action@v2.0.0
